# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cb586dbe835d408f00deac06e0c997587154ee0dca82ca6afcd1cdccffec0674c98240d492d39cc7190589f069171e6daf14757adfcdb70a7163acf8e885b6d

test:
  secret_key_base: cc45aeb49df0218aa78f9cdbcc48d1284df65d6e5ac94822cb861003bed6cf5a001d09d228ff2846ba8756e084e81023d6f2b3aac00f169b4489df40db8b2887

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
